server:
  port: 8080

spring:
#  config:
#    activate:
#      on-profile: local
#      session 용도가 아니면 안써도 ㄱㅊ
  redis:
    host: localhost
    port: 6379



  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
jwt:
  expiration : 300
  secretKey : my_token_secret
  expirationRT : 14400
  secretKeyRT : hackerton_secret

#aws s3 설정
cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test

    region:
      static: ap-northeast-2
    s3:
      bucket: please-file

